### ISSUE TITLE
How I can setup and create new project or debug my existing project?

### ISSUE THREAD

**Issue by krishnakumar-mob-incedo** [willowtreeapps/ukor#37]
How I can setup and create new project or debug my existing project?

I am always getting below issue:
C:\WINDOWS\system32>Ukor init
C:\Users\Krishna.Kumar\AppData\Roaming\npm\node_modules\@willowtreeapps\ukor\bin\ukor-init.js:4
  fs.mkdir('./src', () => {
                     ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\WINDOWS\system32>ukor make
C:\Users\Krishna.Kumar\AppData\Roaming\npm\node_modules\@willowtreeapps\ukor\bin\ukor-make.js:15
let args = program.args
    ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by nishtahir** [comment]
Looks like we aren't resolving the path correctly on Windows.

**Comment by krishnakumar-mob-incedo** [comment]
So, what I have to do?
Please, suggest me, as I am blocked.

**Comment by krishnakumar-mob-incedo** [comment]
Hi 
I also tried on Linux and when running below command, getting error
ukor init

Error:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by nishtahir** [comment]
The windows issue is a bug and we are working on a fix for it. You don't need to do anything for now. 
Looks like the linux issue is a separate problem. Can you open another issue for it?

**Comment by krishnakumar-mob-incedo** [comment]
Reported Linux issue as separate problem.
https://github.com/willowtreeapps/ukor/issues/39

**Comment by vannuysm** [comment]
@krishnakumar-mob-incedo Does this work for you on Windows with a newer version of Node? Also of note is to make sure you don't run the command in `C:\Windows\system32` as that's a protected system folder and you will not be able to write to it.
