### ISSUE TITLE
Tried on Linux and got error while running ukor init and ukor make command. Please help on this.

### ISSUE THREAD

**Issue by krishnakumar-mob-incedo** [willowtreeapps/ukor#39]
Hi
I also tried on Linux and when running below command, getting error
ukor init

Error:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3

**Comment by krishnakumar-mob-incedo** [comment]
I added 'use strict'; in that file now above issue solve but getting another error in another file:
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ukor/node_modules/@willowtreeapps/wist/lib/api.js:2:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by vannuysm** [comment]
Hi @krishnakumar-mob-incedo, thanks for digging into this issue. Can you run `node -v` from your shell and post your results here? That may help narrow down the issue.

**Comment by krishnakumar-mob-incedo** [comment]
result of this command:
v4.2.6

**Comment by vannuysm** [comment]
That would explain it. The minimum version of node needed to run ukor is v7. I would recommend installing v8 as it is the latest LTS release. You can find instructions on how to upgrade for your Linux distribution [on the node website](https://nodejs.org/en/download/package-manager/).

**Comment by krishnakumar-mob-incedo** [comment]
Thank you so much.
Now I am able to run both the commands successfully.

**Comment by vannuysm** [comment]
That's great news, glad it worked for you. Definitely we should mention this in the README. I'll keep this issue open so that we can address that issue.
